name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


env: 
  docker_username: camillafrank
  docker_password: ${{ secrets.GITHUB_TOKEN }}
  GIT_COMMIT: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build
        working-directory: ./frontend
        run: go build -v

      - name: Upload repo
        uses: actions/upload-artifact@v4
        with:
          name: code
          path: .
          include-hidden-files: true

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .

      - name: Run Tests
        working-directory: ./frontend
        run: go test -v

  docker-image-push:
    runs-on: ubuntu-latest
    needs: build
    permissions: 
      packages: write
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with: 
          name: code
          path: .
      - name: build docker
        run: bash ci/build-docker.sh
      - name: push docker
        run: bash ci/push-docker.sh

  deploy:
    needs: docker-image-push
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: Set kubeconfig
        run: echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig
      - name: Apply deployment
        run: kubectl --kubeconfig kubeconfig apply -f ./kubernetes
      - name: Get service IP
        run: |
          # Wait for the service to get an external IP
          kubectl --kubeconfig kubeconfig rollout status deployment/frontend --timeout=120s
          SERVICE_IP=$(kubectl --kubeconfig kubeconfig get svc load-service -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          echo "APP_URL=http://${SERVICE_IP}:8080" >> $GITHUB_ENV
          echo "APP_URL=http://${SERVICE_IP}:8080" >> service_url.txt
      - name: Upload service URL
        uses: actions/upload-artifact@v4
        with:
          name: service-url
          path: service_url.txt

  functional-test:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: Download service URL
        uses: actions/download-artifact@v4
        with:
          name: service-url
      - name: Run functional test
        run: |
          APP_URL=$(cat service_url.txt)
          chmod +x ci/test-app.sh
          APP_URL=$APP_URL ci/test-app.sh


