name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build
        working-directory: ./frontend
        run: go build -v

      - name: Upload repo (optional)
        uses: actions/upload-artifact@v4
        with:
          name: code
          path: .
          include-hidden-files: true

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Download code (optional)
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .

      - name: Run Tests
        working-directory: ./frontend
        run: go test -v
